/* TT-sensei/taiseki から移植した算数教材向け共通SVG立体描画エンジン。 */
(function(global){
'use strict';
const NS='http://www.w3.org/2000/svg';
function el(tag,attrs,text){const n=document.createElementNS(NS,tag);Object.entries(attrs||{}).forEach(([k,v])=>n.setAttribute(k,v));if(text!==undefined)n.textContent=text;return n;}
function polygonPoints(points){return points.map(p=>`${p.x.toFixed(2)},${p.y.toFixed(2)}`).join(' ');}
function regularPolygon(sides,radius,rotation){const a=[];for(let i=0;i<sides;i++){const t=rotation+Math.PI*2*i/sides;a.push([radius*Math.cos(t),radius*Math.sin(t)]);}return a;}
function baseForShape(shape,d,circleSides){d=d||{};switch(shape){case'square':{const s=d.side||5;return[[-s/2,-s/2],[s/2,-s/2],[s/2,s/2],[-s/2,s/2]];}case'rectangle':{const w=d.width||7,q=d.depth||4;return[[-w/2,-q/2],[w/2,-q/2],[w/2,q/2],[-w/2,q/2]];}case'triangle':{const w=d.base||6,q=d.triangleHeight||5;return[[-w/2,q/2],[w/2,q/2],[0,-q/2]];}case'parallelogram':{const w=d.base||7,q=d.baseHeight||4,l=Math.min(w*.28,q*.55);return[[-w/2+l,-q/2],[w/2+l,-q/2],[w/2-l,q/2],[-w/2-l,q/2]];}case'trapezoid':{const t=d.top||4,b=d.bottom||8,q=d.baseHeight||4;return[[-t/2,-q/2],[t/2,-q/2],[b/2,q/2],[-b/2,q/2]];}case'rhombus':{const w=d.diagonal1||7,q=d.diagonal2||5;return[[0,-q/2],[w/2,0],[0,q/2],[-w/2,0]];}case'circle':return regularPolygon(circleSides||48,d.radius||3,-Math.PI/2);default:return baseForShape('rectangle',d,circleSides);}}
function createProjector(o,base,h){const angle=(o.angle===undefined?-42:o.angle)*Math.PI/180,e=(o.elevation===undefined?27:o.elevation)*Math.PI/180,w=o.width||360,hpx=o.height||280,c=Math.cos(angle),s=Math.sin(angle),rise=Math.sin(e);function raw(p){const rx=p.x*c-p.z*s,depth=p.x*s+p.z*c;return{x:rx,y:depth*rise-p.y,depth};}const samples=[];base.forEach(([x,z])=>{samples.push(raw({x,y:0,z}),raw({x,y:h,z}));});const minX=Math.min(...samples.map(p=>p.x)),maxX=Math.max(...samples.map(p=>p.x)),minY=Math.min(...samples.map(p=>p.y)),maxY=Math.max(...samples.map(p=>p.y)),pad=o.padding||{left:34,right:82,top:28,bottom:52},uw=w-pad.left-pad.right,uh=hpx-pad.top-pad.bottom,scale=Math.min(uw/Math.max(1,maxX-minX),uh/Math.max(1,maxY-minY)),ox=pad.left+(uw-(maxX-minX)*scale)/2-minX*scale,oy=pad.top+(uh-(maxY-minY)*scale)/2-minY*scale;return p=>{const q=raw(p);return{x:ox+q.x*scale,y:oy+q.y*scale,depth:q.depth,scale};};}
function line(g,a,b,cls,extra){g.appendChild(el('line',Object.assign({x1:a.x,y1:a.y,x2:b.x,y2:b.y,class:cls},extra||{})));}
function addText(g,p,text,cls,attrs){g.appendChild(el('text',Object.assign({x:p.x,y:p.y,class:cls},attrs||{}),text));}
function addDimension(g,project,spec){const a=project(spec.from),b=project(spec.to),dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy)||1,nx=-dy/len,ny=dx/len,o=spec.offset||0,p1={x:a.x+nx*o,y:a.y+ny*o},p2={x:b.x+nx*o,y:b.y+ny*o},cls=spec.role==='height'?'solid-dimension solid-height-dimension':'solid-dimension';line(g,p1,p2,cls);const t=5;line(g,{x:p1.x-nx*t,y:p1.y-ny*t},{x:p1.x+nx*t,y:p1.y+ny*t},cls);line(g,{x:p2.x-nx*t,y:p2.y-ny*t},{x:p2.x+nx*t,y:p2.y+ny*t},cls);addText(g,{x:(p1.x+p2.x)/2+nx*13,y:(p1.y+p2.y)/2+ny*13},spec.text,`solid-dimension-text${spec.role==='height'?' solid-height-text':''}`,{'text-anchor':'middle'});}
function renderPrism(svg,o){const c=Object.assign({width:360,height:280,shape:'rectangle',solidHeight:6,color:'#1FA6A0',baseColor:'#ff5d5d',showHiddenEdges:true,circleSides:48,layers:0},o||{}),base=c.base||baseForShape(c.shape,c.dimensions,c.circleSides),h=Math.max(.25,Number(c.solidHeight)||1),project=createProjector(c,base,h),bottom=base.map(([x,z])=>project({x,y:0,z})),top=base.map(([x,z])=>project({x,y:h,z})),center=project({x:0,y:0,z:0});svg.setAttribute('viewBox',`0 0 ${c.width} ${c.height}`);svg.innerHTML='';const scene=el('g',{class:'solid-scene'});svg.appendChild(scene);const sides=base.map((_,i)=>{const n=(i+1)%base.length,depth=(bottom[i].depth+bottom[n].depth)/2;return{i,next:n,depth,front:(bottom[i].y+bottom[n].y)/2>=center.y};}).sort((a,b)=>a.depth-b.depth);sides.forEach(s=>{if(s.front)scene.appendChild(el('polygon',{points:polygonPoints([top[s.i],top[s.next],bottom[s.next],bottom[s.i]]),class:'solid-side-face',fill:c.color}));});scene.appendChild(el('polygon',{points:polygonPoints(bottom),class:'solid-base-face',fill:c.baseColor}));if(c.layers>1)for(let layer=1;layer<c.layers;layer++){const y=h*layer/c.layers,ring=base.map(([x,z])=>project({x,y,z}));scene.appendChild(el('polygon',{points:polygonPoints(ring),class:'solid-layer-line'}));}if(c.shape==='circle'&&c.circleSides>=20){const ids=[bottom.reduce((b,p,j)=>p.x<bottom[b].x?j:b,0),bottom.reduce((b,p,j)=>p.x>bottom[b].x?j:b,0)];ids.forEach(j=>line(scene,top[j],bottom[j],'solid-edge'));}else sides.forEach(s=>{const cls=s.front?'solid-edge':'solid-edge solid-hidden-edge';if(s.front||c.showHiddenEdges)line(scene,top[s.i],bottom[s.i],cls);});sides.forEach(s=>{const cls=s.front?'solid-base-edge':'solid-base-edge solid-hidden-edge';if(s.front||c.showHiddenEdges)line(scene,bottom[s.i],bottom[s.next],cls);});scene.appendChild(el('polygon',{points:polygonPoints(top),class:'solid-top-face',fill:c.color}));if(Array.isArray(c.internalLines))c.internalLines.forEach(spec=>line(scene,project(spec.from),project(spec.to),spec.role==='base'?'solid-base-helper':'solid-helper'));const ann=el('g',{class:'solid-annotations'});svg.appendChild(ann);(c.dimensionsToShow||[]).forEach(spec=>addDimension(ann,project,spec));if(c.baseLabel)addText(ann,{x:center.x,y:center.y+18},c.baseLabel,'solid-base-label',{'text-anchor':'middle'});return{project,base,bottom,top};}
global.SolidSVG={renderPrism,baseForShape,regularPolygon};
})(window);
